# WHP Profile for PowerPC Systems

CONFIG_LED=y
CONFIG_MAC_OLDWORLD=y
CONFIG_MAC_NEWWORLD=y
CONFIG_NE2000_PCI=y
CONFIG_PCI_DEVICES=y
CONFIG_SUNGEM=y
CONFIG_TEST_DEVICES=y
CONFIG_USB_HID=y
CONFIG_USB_HUB=y
CONFIG_USB_OHCI_PCI=y
CONFIG_VGA_PCI=y
