#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="${1:-}"
OUTPUT="${2:-}"

if [[ -z "$CONFIG_FILE" || -z "$OUTPUT" ]]; then
    printf 'usage: %s CONFIG_FILE OUTPUT\n' "$0" >&2
    exit 2
fi
if [[ ! -f "$CONFIG_FILE" ]]; then
    printf 'error: OpenBIOS Meson config is missing: %s\n' "$CONFIG_FILE" >&2
    exit 1
fi
case "$CONFIG_FILE" in
    *$'\n'*|*$'\r'*)
        printf 'error: invalid OpenBIOS Meson config path\n' >&2
        exit 1
        ;;
esac

# This file is generated by scripts/macos-builder.bash with printf %q and is
# owned by the current QEMU build directory.
# shellcheck disable=SC1090
source "$CONFIG_FILE"

: "${OPENBIOS_TOOLS_DIR:?OPENBIOS_TOOLS_DIR is required}"
: "${OPENBIOS_HOSTCC:?OPENBIOS_HOSTCC is required}"
: "${OPENBIOS_HOSTCXX:?OPENBIOS_HOSTCXX is required}"
: "${OPENBIOS_HOSTSTRIP:?OPENBIOS_HOSTSTRIP is required}"
: "${POWERPC_TOOLCHAIN_DIR:?POWERPC_TOOLCHAIN_DIR is required}"
: "${POWERPC_TOOLCHAIN_WORK_DIR:?POWERPC_TOOLCHAIN_WORK_DIR is required}"
: "${POWERPC_TOOLCHAIN_DOWNLOAD_DIR:?POWERPC_TOOLCHAIN_DOWNLOAD_DIR is required}"

case "${POWERPC_TOOLCHAIN_SOURCE_MODE:-release}" in
    release)
        bootstrap_script="$SCRIPT_DIR/bootstrap-powerpc-toolchain-host.sh"
        ;;
    git)
        bootstrap_script="$SCRIPT_DIR/bootstrap-powerpc-toolchain-git.sh"
        ;;
    *)
        printf 'error: POWERPC_TOOLCHAIN_SOURCE_MODE must be release or git\n' >&2
        exit 1
        ;;
esac

case "$OUTPUT" in
    /*) ;;
    *) OUTPUT="$PWD/$OUTPUT" ;;
esac
mkdir -p "$(dirname "$OUTPUT")"

cross_prefix="${OPENBIOS_CROSS_COMPILE:-}"
if [[ -z "$cross_prefix" && "${BOOTSTRAP_POWERPC_TOOLCHAIN:-1}" == 1 ]]; then
    env -u CFLAGS -u CXXFLAGS -u OBJCFLAGS -u CPPFLAGS -u LDFLAGS \
        POWERPC_TOOLCHAIN_DIR="$POWERPC_TOOLCHAIN_DIR" \
        POWERPC_TOOLCHAIN_WORK_DIR="$POWERPC_TOOLCHAIN_WORK_DIR" \
        POWERPC_TOOLCHAIN_DOWNLOAD_DIR="$POWERPC_TOOLCHAIN_DOWNLOAD_DIR" \
        POWERPC_TOOLCHAIN_FORCE_REBUILD="${POWERPC_TOOLCHAIN_FORCE_REBUILD:-0}" \
        POWERPC_TOOLCHAIN_HOST_CC="$OPENBIOS_HOSTCC" \
        POWERPC_TOOLCHAIN_HOST_CXX="$OPENBIOS_HOSTCXX" \
        TOOLCHAIN_HOST_CC="$OPENBIOS_HOSTCC" \
        TOOLCHAIN_HOST_CXX="$OPENBIOS_HOSTCXX" \
        TOOLCHAIN_HOST_STRIP="$OPENBIOS_HOSTSTRIP" \
        CC_FOR_BUILD="$OPENBIOS_HOSTCC" \
        CXX_FOR_BUILD="$OPENBIOS_HOSTCXX" \
        STRIP_FOR_BUILD="$OPENBIOS_HOSTSTRIP" \
        CONFIG_SHELL="${CONFIG_SHELL:-/bin/bash}" \
        MAKE_CMD="${MAKE_CMD:-make}" \
        JOBS="${JOBS:-1}" \
        POWERPC_TOOLCHAIN_GIT_OFFLINE="${POWERPC_TOOLCHAIN_GIT_OFFLINE:-0}" \
        POWERPC_BINUTILS_GIT_URL="${POWERPC_BINUTILS_GIT_URL:-https://sourceware.org/git/binutils-gdb.git}" \
        POWERPC_BINUTILS_GIT_REF="${POWERPC_BINUTILS_GIT_REF:-binutils-2_46-branch}" \
        POWERPC_BINUTILS_GIT_COMMIT="${POWERPC_BINUTILS_GIT_COMMIT:-}" \
        POWERPC_GCC_GIT_URL="${POWERPC_GCC_GIT_URL:-https://gcc.gnu.org/git/gcc.git}" \
        POWERPC_GCC_GIT_REF="${POWERPC_GCC_GIT_REF:-releases/gcc-16}" \
        POWERPC_GCC_GIT_COMMIT="${POWERPC_GCC_GIT_COMMIT:-}" \
        bash "$bootstrap_script"
    cross_prefix="$POWERPC_TOOLCHAIN_DIR/bin/powerpc-elf-"
fi

if [[ -z "$cross_prefix" ]]; then
    printf 'error: no PowerPC cross-toolchain is available for OpenBIOS\n' >&2
    exit 1
fi
for tool in gcc as ar ld nm strip ranlib; do
    if [[ ! -x "${cross_prefix}${tool}" ]]; then
        printf 'error: incomplete PowerPC cross-toolchain: %s%s\n' \
            "$cross_prefix" "$tool" >&2
        exit 1
    fi
done

env -u CFLAGS -u CXXFLAGS -u OBJCFLAGS -u CPPFLAGS -u LDFLAGS \
    OPENBIOS_DIR="${OPENBIOS_DIR:-$SOURCE_DIR/roms/openbios}" \
    OPENBIOS_OUTPUT="$OUTPUT" \
    OPENBIOS_TOOLS_DIR="$OPENBIOS_TOOLS_DIR" \
    OPENBIOS_HOSTCC="$OPENBIOS_HOSTCC" \
    OPENBIOS_HOSTCXX="$OPENBIOS_HOSTCXX" \
    OPENBIOS_HOSTSTRIP="$OPENBIOS_HOSTSTRIP" \
    OPENBIOS_TOKE="${OPENBIOS_TOKE:-}" \
    OPENBIOS_CROSS_COMPILE="$cross_prefix" \
    OPENBIOS_FORCE_RECONFIGURE="${OPENBIOS_FORCE_RECONFIGURE:-0}" \
    BOOTSTRAP_POWERPC_TOOLCHAIN=0 \
    POWERPC_TOOLCHAIN_DIR="$POWERPC_TOOLCHAIN_DIR" \
    POWERPC_TOOLCHAIN_WORK_DIR="$POWERPC_TOOLCHAIN_WORK_DIR" \
    POWERPC_TOOLCHAIN_DOWNLOAD_DIR="$POWERPC_TOOLCHAIN_DOWNLOAD_DIR" \
    CC_FOR_BUILD="$OPENBIOS_HOSTCC" \
    CXX_FOR_BUILD="$OPENBIOS_HOSTCXX" \
    STRIP_FOR_BUILD="$OPENBIOS_HOSTSTRIP" \
    PKG_CONFIG_FOR_BUILD="${PKG_CONFIG_FOR_BUILD:-pkg-config}" \
    MAKE_CMD="${MAKE_CMD:-make}" \
    JOBS="${JOBS:-1}" \
    bash "$SCRIPT_DIR/build-openbios.sh"

if [[ ! -s "$OUTPUT" ]]; then
    printf 'error: Meson OpenBIOS target did not produce %s\n' "$OUTPUT" >&2
    exit 1
fi
