#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="${1:-}"
OUTPUT="${2:-}"
OPENBIOS_ENVIRONMENT_POLICY=4

if [[ -z "$CONFIG_FILE" || -z "$OUTPUT" ]]; then
    printf 'usage: %s CONFIG_FILE OUTPUT\n' "$0" >&2
    exit 2
fi
if [[ ! -f "$CONFIG_FILE" ]]; then
    printf 'error: OpenBIOS Meson config is missing: %s\n' "$CONFIG_FILE" >&2
    exit 1
fi
case "$CONFIG_FILE" in
    *$'\n'*|*$'\r'*)
        printf 'error: invalid OpenBIOS Meson config path\n' >&2
        exit 1
        ;;
esac

# This file is generated by scripts/whp-build/configure-openbios.bash with
# printf %q and is owned by the current QEMU build directory.
# shellcheck disable=SC1090
source "$CONFIG_FILE"

: "${OPENBIOS_BUILD_DIR:?OPENBIOS_BUILD_DIR is required}"
: "${OPENBIOS_TOOLS_DIR:?OPENBIOS_TOOLS_DIR is required}"
: "${OPENBIOS_HOSTCC:?OPENBIOS_HOSTCC is required}"
: "${OPENBIOS_HOSTCXX:?OPENBIOS_HOSTCXX is required}"
: "${OPENBIOS_HOSTSTRIP:?OPENBIOS_HOSTSTRIP is required}"
: "${POWERPC_TOOLCHAIN_DIR:?POWERPC_TOOLCHAIN_DIR is required}"
: "${POWERPC_TOOLCHAIN_WORK_DIR:?POWERPC_TOOLCHAIN_WORK_DIR is required}"
: "${POWERPC_TOOLCHAIN_DOWNLOAD_DIR:?POWERPC_TOOLCHAIN_DOWNLOAD_DIR is required}"

# Keep local builds on the repaired project fork.  Use a distinct cache path
# so an older vanilla checkout cannot retain its origin or obsolete Makefile.
FCODE_UTILS_REPOSITORY="${FCODE_UTILS_REPOSITORY:-https://github.com/retrochristian5000/fcode-utils.git}"
FCODE_UTILS_REV="${FCODE_UTILS_REV:-b9b6da855f2e698f8163ebd22227fc43d6eef7f4}"
FCODE_UTILS_DIR="${FCODE_UTILS_DIR:-$OPENBIOS_TOOLS_DIR/fcode-utils-retrochristian5000}"

# QEMU's host build may legitimately use Homebrew and pkg-config.  OpenBIOS is
# a freestanding firmware sub-build and must not inherit those search paths.
# In particular, GCC consults CPATH, COMPILER_PATH, GCC_EXEC_PREFIX, and
# LIBRARY_PATH even when its command line contains otherwise clean flags.
openbios_clean_env=(
    env
    -u CC -u CXX -u OBJC
    -u CFLAGS -u CXXFLAGS -u OBJCFLAGS -u CPPFLAGS -u LDFLAGS
    -u HOSTCFLAGS -u HOSTCPPFLAGS -u HOSTLDFLAGS
    -u CFLAGS_FOR_BUILD -u CXXFLAGS_FOR_BUILD
    -u CPPFLAGS_FOR_BUILD -u LDFLAGS_FOR_BUILD
    -u CFLAGS_FOR_TARGET -u CXXFLAGS_FOR_TARGET
    -u CPPFLAGS_FOR_TARGET -u LDFLAGS_FOR_TARGET
    -u CPATH -u C_INCLUDE_PATH -u CPLUS_INCLUDE_PATH -u OBJC_INCLUDE_PATH
    -u COMPILER_PATH -u GCC_EXEC_PREFIX -u LIBRARY_PATH
    -u LD_LIBRARY_PATH -u DYLD_LIBRARY_PATH -u DYLD_FALLBACK_LIBRARY_PATH
    -u DYLD_INSERT_LIBRARIES
    -u PKG_CONFIG_PATH -u PKG_CONFIG_LIBDIR -u PKG_CONFIG_SYSROOT_DIR
    -u CMAKE_PREFIX_PATH -u CMAKE_LIBRARY_PATH -u CMAKE_INCLUDE_PATH
    -u ACLOCAL_PATH -u ARCHFLAGS
)

source_mode="${POWERPC_TOOLCHAIN_SOURCE_MODE:-release}"
compiler_mode="${POWERPC_TOOLCHAIN_COMPILER:-}"
if [[ -z "$compiler_mode" ]]; then
    case "$(uname -s)" in
        Darwin) compiler_mode=clang ;;
        *) compiler_mode=gcc ;;
    esac
fi
case "$compiler_mode" in
    clang)
        # This is intentionally a compiler-only migration.  GNU binutils stay
        # on the same pinned release path while Clang comes from the WHP fork.
        if [[ "$source_mode" != release ]]; then
            printf '%s\n' \
                'error: the PowerPC Clang lane currently retains release binutils.' \
                'set POWERPC_TOOLCHAIN_SOURCE_MODE=release or unset it.' >&2
            exit 1
        fi
        bootstrap_script="$SCRIPT_DIR/bootstrap-powerpc-clang.sh"
        ;;
    gcc)
        case "$source_mode" in
            release)
                bootstrap_script="$SCRIPT_DIR/bootstrap-powerpc-toolchain-host.sh"
                ;;
            git)
                bootstrap_script="$SCRIPT_DIR/bootstrap-powerpc-toolchain-git.sh"
                ;;
            *)
                printf 'error: POWERPC_TOOLCHAIN_SOURCE_MODE must be release or git\n' >&2
                exit 1
                ;;
        esac
        ;;
    *)
        printf 'error: POWERPC_TOOLCHAIN_COMPILER must be clang or gcc\n' >&2
        exit 1
        ;;
esac

case "${POWERPC_BINUTILS_GIT_REF:-}" in
    ''|binutils-2_46-branch)
        POWERPC_BINUTILS_GIT_REF=binutils_2.46-branch
        ;;
esac

if [[ "$compiler_mode" == gcc && "$source_mode" == git ]]; then
    case "$OPENBIOS_HOSTCXX" in
        ''|*';'*|*'|'*|*'&'*|*'<'*|*'>')
            printf 'error: invalid OpenBIOS host C++ compiler command\n' >&2
            exit 1
            ;;
    esac
    read -r -a host_cxx_command <<< "$OPENBIOS_HOSTCXX"
    if [[ "${#host_cxx_command[@]}" -eq 0 ]] ||
       ! command -v "${host_cxx_command[0]}" >/dev/null 2>&1; then
        printf 'error: OpenBIOS host C++ compiler is not executable: %s\n' \
            "$OPENBIOS_HOSTCXX" >&2
        exit 1
    fi
    if ! printf '%s\n' \
        'static_assert(__cplusplus >= 201402L, "ISO C++14 required");' |
        "${openbios_clean_env[@]}" "${host_cxx_command[@]}" \
            -std=c++14 -x c++ -fsyntax-only - >/dev/null 2>&1; then
        printf '%s\n' \
            'error: official GCC 16 Git sources require an ISO C++14 host compiler.' \
            "selected: $OPENBIOS_HOSTCXX" >&2
        exit 1
    fi
fi

case "$OUTPUT" in
    /*) ;;
    *) OUTPUT="$PWD/$OUTPUT" ;;
esac
mkdir -p "$(dirname "$OUTPUT")"

case "$OPENBIOS_BUILD_DIR" in
    /|'')
        printf 'error: unsafe OpenBIOS build directory: %s\n' \
            "$OPENBIOS_BUILD_DIR" >&2
        exit 1
        ;;
esac
environment_policy_file="$OPENBIOS_BUILD_DIR/.whp-openbios-environment-policy"
effective_force_reconfigure="${OPENBIOS_FORCE_RECONFIGURE:-0}"
if [[ ! -f "$environment_policy_file" ]] ||
   [[ "$(cat "$environment_policy_file" 2>/dev/null || true)" != \
      "$OPENBIOS_ENVIRONMENT_POLICY" ]]; then
    effective_force_reconfigure=1
    printf '%s\n' \
        'OpenBIOS environment policy changed; forcing a clean firmware rebuild.' \
        "policy: $OPENBIOS_ENVIRONMENT_POLICY"
fi

cross_prefix="${OPENBIOS_CROSS_COMPILE:-}"
if [[ -z "$cross_prefix" && "${BOOTSTRAP_POWERPC_TOOLCHAIN:-1}" == 1 ]]; then
    printf 'PowerPC firmware compiler: %s\n' "$compiler_mode"
    "${openbios_clean_env[@]}" \
        POWERPC_TOOLCHAIN_DIR="$POWERPC_TOOLCHAIN_DIR" \
        POWERPC_TOOLCHAIN_WORK_DIR="$POWERPC_TOOLCHAIN_WORK_DIR" \
        POWERPC_TOOLCHAIN_DOWNLOAD_DIR="$POWERPC_TOOLCHAIN_DOWNLOAD_DIR" \
        POWERPC_TOOLCHAIN_FORCE_REBUILD="${POWERPC_TOOLCHAIN_FORCE_REBUILD:-0}" \
        POWERPC_TOOLCHAIN_HOST_CC="$OPENBIOS_HOSTCC" \
        POWERPC_TOOLCHAIN_HOST_CXX="$OPENBIOS_HOSTCXX" \
        TOOLCHAIN_HOST_CC="$OPENBIOS_HOSTCC" \
        TOOLCHAIN_HOST_CXX="$OPENBIOS_HOSTCXX" \
        TOOLCHAIN_HOST_STRIP="$OPENBIOS_HOSTSTRIP" \
        CC_FOR_BUILD="$OPENBIOS_HOSTCC" \
        CXX_FOR_BUILD="$OPENBIOS_HOSTCXX" \
        STRIP_FOR_BUILD="$OPENBIOS_HOSTSTRIP" \
        CONFIG_SHELL="${CONFIG_SHELL:-/bin/bash}" \
        MAKE_CMD="${MAKE_CMD:-make}" \
        JOBS="${JOBS:-1}" \
        POWERPC_TOOLCHAIN_GIT_OFFLINE="${POWERPC_TOOLCHAIN_GIT_OFFLINE:-0}" \
        POWERPC_BINUTILS_GIT_URL="${POWERPC_BINUTILS_GIT_URL:-https://sourceware.org/git/binutils-gdb.git}" \
        POWERPC_BINUTILS_GIT_REF="$POWERPC_BINUTILS_GIT_REF" \
        POWERPC_BINUTILS_GIT_COMMIT="${POWERPC_BINUTILS_GIT_COMMIT:-}" \
        POWERPC_GCC_GIT_URL="${POWERPC_GCC_GIT_URL:-https://gcc.gnu.org/git/gcc.git}" \
        POWERPC_GCC_GIT_REF="${POWERPC_GCC_GIT_REF:-releases/gcc-16}" \
        POWERPC_GCC_GIT_COMMIT="${POWERPC_GCC_GIT_COMMIT:-}" \
        POWERPC_LLVM_GIT_URL="${POWERPC_LLVM_GIT_URL:-https://github.com/retrochristian5000/LLVM.git}" \
        POWERPC_LLVM_GIT_REF="${POWERPC_LLVM_GIT_REF:-main}" \
        POWERPC_LLVM_GIT_COMMIT="${POWERPC_LLVM_GIT_COMMIT:-e7dd336e0f7884c34108a1e722205a16c3f5307b}" \
        POWERPC_LLVM_GIT_OFFLINE="${POWERPC_LLVM_GIT_OFFLINE:-0}" \
        bash "$bootstrap_script"
    cross_prefix="$POWERPC_TOOLCHAIN_DIR/bin/powerpc-elf-"
fi

if [[ -z "$cross_prefix" ]]; then
    printf 'error: no PowerPC cross-toolchain is available for OpenBIOS\n' >&2
    exit 1
fi
for tool in gcc as ar ld nm strip ranlib; do
    if [[ ! -x "${cross_prefix}${tool}" ]]; then
        printf 'error: incomplete PowerPC cross-toolchain: %s%s\n' \
            "$cross_prefix" "$tool" >&2
        exit 1
    fi
done

"${openbios_clean_env[@]}" \
    OPENBIOS_DIR="${OPENBIOS_DIR:-$SOURCE_DIR/roms/openbios}" \
    OPENBIOS_BUILD_DIR="$OPENBIOS_BUILD_DIR" \
    OPENBIOS_OUTPUT="$OUTPUT" \
    OPENBIOS_TOOLS_DIR="$OPENBIOS_TOOLS_DIR" \
    OPENBIOS_HOSTCC="$OPENBIOS_HOSTCC" \
    OPENBIOS_HOSTCXX="$OPENBIOS_HOSTCXX" \
    OPENBIOS_HOSTSTRIP="$OPENBIOS_HOSTSTRIP" \
    OPENBIOS_READELF="${OPENBIOS_READELF:-}" \
    OPENBIOS_TOKE="${OPENBIOS_TOKE:-}" \
    FCODE_UTILS_REPOSITORY="$FCODE_UTILS_REPOSITORY" \
    FCODE_UTILS_REV="$FCODE_UTILS_REV" \
    FCODE_UTILS_DIR="$FCODE_UTILS_DIR" \
    OPENBIOS_CROSS_COMPILE="$cross_prefix" \
    OPENBIOS_FORCE_RECONFIGURE="$effective_force_reconfigure" \
    BOOTSTRAP_POWERPC_TOOLCHAIN=0 \
    POWERPC_TOOLCHAIN_DIR="$POWERPC_TOOLCHAIN_DIR" \
    POWERPC_TOOLCHAIN_WORK_DIR="$POWERPC_TOOLCHAIN_WORK_DIR" \
    POWERPC_TOOLCHAIN_DOWNLOAD_DIR="$POWERPC_TOOLCHAIN_DOWNLOAD_DIR" \
    CC_FOR_BUILD="$OPENBIOS_HOSTCC" \
    CXX_FOR_BUILD="$OPENBIOS_HOSTCXX" \
    STRIP_FOR_BUILD="$OPENBIOS_HOSTSTRIP" \
    PKG_CONFIG_FOR_BUILD=false \
    MAKE_CMD="${MAKE_CMD:-make}" \
    JOBS="${JOBS:-1}" \
    bash "$SCRIPT_DIR/build-openbios.sh"

if [[ ! -s "$OUTPUT" ]]; then
    printf 'error: Meson OpenBIOS target did not produce %s\n' "$OUTPUT" >&2
    exit 1
fi

mkdir -p "$OPENBIOS_BUILD_DIR"
printf '%s\n' "$OPENBIOS_ENVIRONMENT_POLICY" \
    > "$environment_policy_file.new"
mv -f "$environment_policy_file.new" "$environment_policy_file"
printf 'OpenBIOS environment: isolated from host package search paths\n'
